tupla = tuple()
tupla = ()
type(tupla)
dir(tupla)
# help(tuple)
type(tupla)
tupla = ('um') # Nao eh uma tupla e sim String
type(tupla)
tupla = ('um',)
type(tupla)
print(tupla[0])
# tupla[0] = 'novo'
cores = ('verde', 'amarelo', 'azul', 'branco')
print(cores[0])
print(cores[-1])
print(cores[1:])
print(cores.index('amarelo'))
print(cores.count('Azul'))
print(cores.count('azul'))
len(cores)